[build]
  # Simple static deployment
  command = "node simple-deploy.js"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200